[package]
name = "convert_temp"
version = "0.1.0"
authors = ["Robert C. Alfredson <robert.c.alfredson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
